// flow-typed signature: 8eb6a161463e36bd3fd889bb5205a66b
// flow-typed version: <<STUB>>/karma-safari-launcher_v^1.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-safari-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-safari-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'karma-safari-launcher/index' {
  declare module.exports: $Exports<'karma-safari-launcher'>;
}
declare module 'karma-safari-launcher/index.js' {
  declare module.exports: $Exports<'karma-safari-launcher'>;
}
