// flow-typed signature: 186ac4956d28f1821c3c6044300ddbdb
// flow-typed version: <<STUB>>/karma-time-stats-reporter_v^0.1.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-time-stats-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-time-stats-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-time-stats-reporter/test/integration/examples/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-time-stats-reporter/test/integration/examples/quick.spec' {
  declare module.exports: any;
}

declare module 'karma-time-stats-reporter/test/integration/examples/single_slow_example.spec' {
  declare module.exports: any;
}

declare module 'karma-time-stats-reporter/test/integration/examples/ten_progressively_slow.spec' {
  declare module.exports: any;
}

declare module 'karma-time-stats-reporter/test/integration/examples/three_slow_examples.spec' {
  declare module.exports: any;
}

declare module 'karma-time-stats-reporter/test/unit/karma-time-stats-reporter.spec' {
  declare module.exports: any;
}

declare module 'karma-time-stats-reporter/test/unit/karma.unit.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-time-stats-reporter/index' {
  declare module.exports: $Exports<'karma-time-stats-reporter'>;
}
declare module 'karma-time-stats-reporter/index.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter'>;
}
declare module 'karma-time-stats-reporter/test/integration/examples/karma.conf.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/integration/examples/karma.conf'>;
}
declare module 'karma-time-stats-reporter/test/integration/examples/quick.spec.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/integration/examples/quick.spec'>;
}
declare module 'karma-time-stats-reporter/test/integration/examples/single_slow_example.spec.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/integration/examples/single_slow_example.spec'>;
}
declare module 'karma-time-stats-reporter/test/integration/examples/ten_progressively_slow.spec.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/integration/examples/ten_progressively_slow.spec'>;
}
declare module 'karma-time-stats-reporter/test/integration/examples/three_slow_examples.spec.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/integration/examples/three_slow_examples.spec'>;
}
declare module 'karma-time-stats-reporter/test/unit/karma-time-stats-reporter.spec.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/unit/karma-time-stats-reporter.spec'>;
}
declare module 'karma-time-stats-reporter/test/unit/karma.unit.conf.js' {
  declare module.exports: $Exports<'karma-time-stats-reporter/test/unit/karma.unit.conf'>;
}
