// flow-typed signature: aee3e14f8ac48db39f2df31cc4d95381
// flow-typed version: <<STUB>>/karma-ie-launcher_v^1.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-ie-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-ie-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-ie-launcher/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-ie-launcher/test/launcher.spec' {
  declare module.exports: any;
}

declare module 'karma-ie-launcher/test/mocha-globals' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-ie-launcher/gruntfile.js' {
  declare module.exports: $Exports<'karma-ie-launcher/gruntfile'>;
}
declare module 'karma-ie-launcher/index' {
  declare module.exports: $Exports<'karma-ie-launcher'>;
}
declare module 'karma-ie-launcher/index.js' {
  declare module.exports: $Exports<'karma-ie-launcher'>;
}
declare module 'karma-ie-launcher/test/launcher.spec.js' {
  declare module.exports: $Exports<'karma-ie-launcher/test/launcher.spec'>;
}
declare module 'karma-ie-launcher/test/mocha-globals.js' {
  declare module.exports: $Exports<'karma-ie-launcher/test/mocha-globals'>;
}
