// flow-typed signature: 58808f908cebf347afedde681f082a94
// flow-typed version: <<STUB>>/karma-stacktrace_v^2.0.2/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-stacktrace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-stacktrace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-stacktrace/lib' {
  declare module.exports: any;
}

declare module 'karma-stacktrace/lib/stacktrace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-stacktrace/index' {
  declare module.exports: $Exports<'karma-stacktrace'>;
}
declare module 'karma-stacktrace/index.js' {
  declare module.exports: $Exports<'karma-stacktrace'>;
}
declare module 'karma-stacktrace/lib/index' {
  declare module.exports: $Exports<'karma-stacktrace/lib'>;
}
declare module 'karma-stacktrace/lib/index.js' {
  declare module.exports: $Exports<'karma-stacktrace/lib'>;
}
declare module 'karma-stacktrace/lib/stacktrace.js' {
  declare module.exports: $Exports<'karma-stacktrace/lib/stacktrace'>;
}
