// flow-typed signature: 4289858b8478158635cb3825c7f8c4b5
// flow-typed version: <<STUB>>/karma-source-map-support_v^1.4.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-source-map-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-source-map-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-source-map-support/lib/client' {
  declare module.exports: any;
}

declare module 'karma-source-map-support/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-source-map-support/lib/client.js' {
  declare module.exports: $Exports<'karma-source-map-support/lib/client'>;
}
declare module 'karma-source-map-support/lib/index' {
  declare module.exports: $Exports<'karma-source-map-support/lib'>;
}
declare module 'karma-source-map-support/lib/index.js' {
  declare module.exports: $Exports<'karma-source-map-support/lib'>;
}
