// flow-typed signature: 9f5acd306cb3d6947b98208117814289
// flow-typed version: <<STUB>>/karma-firefox-launcher_v^2.1.1/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-firefox-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-firefox-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-firefox-launcher/commitlint.config' {
  declare module.exports: any;
}

declare module 'karma-firefox-launcher/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-firefox-launcher/release.config' {
  declare module.exports: any;
}

declare module 'karma-firefox-launcher/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-firefox-launcher/commitlint.config.js' {
  declare module.exports: $Exports<'karma-firefox-launcher/commitlint.config'>;
}
declare module 'karma-firefox-launcher/index' {
  declare module.exports: $Exports<'karma-firefox-launcher'>;
}
declare module 'karma-firefox-launcher/index.js' {
  declare module.exports: $Exports<'karma-firefox-launcher'>;
}
declare module 'karma-firefox-launcher/karma.conf.js' {
  declare module.exports: $Exports<'karma-firefox-launcher/karma.conf'>;
}
declare module 'karma-firefox-launcher/release.config.js' {
  declare module.exports: $Exports<'karma-firefox-launcher/release.config'>;
}
declare module 'karma-firefox-launcher/test/index.spec.js' {
  declare module.exports: $Exports<'karma-firefox-launcher/test/index.spec'>;
}
