// flow-typed signature: c276752cdefa1292616607341541b083
// flow-typed version: <<STUB>>/rollup-plugin-polyfill-node_v^0.7.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-polyfill-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-polyfill-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-polyfill-node/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-polyfill-node/dist/index' {
  declare module.exports: $Exports<'rollup-plugin-polyfill-node/dist'>;
}
declare module 'rollup-plugin-polyfill-node/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-polyfill-node/dist'>;
}
