// flow-typed signature: 6eef59165cee0108cc8adc12c3eb05b5
// flow-typed version: <<STUB>>/@rollup/plugin-alias_v^3.1.4/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-alias/dist/index.es' {
  declare module.exports: any;
}

declare module '@rollup/plugin-alias/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-alias/dist/index.es.js' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist/index.es'>;
}
declare module '@rollup/plugin-alias/dist/index' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist'>;
}
declare module '@rollup/plugin-alias/dist/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-alias/dist'>;
}
